name: Generar HTML desde Markdown

on:
  push:
    paths:
      - 'noticias/*.md'
      - '.github/workflows/**'

jobs:
  build-html:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Instalar dependencias
      run: npm install marked

    - name: Convertir Markdown a HTML
      run: |
        CONTENT=$(npx marked noticias/noticias.md)
        TEMPLATE=$(cat noticias/template.html)
        echo "${TEMPLATE//\{\{contenido\}\}/$CONTENT}" > noticias/noticias.html

    - name: Commit y push del HTML generado
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add noticias/noticias.html
        git commit -m "Generar noticias.html desde Markdown" || echo "Sin cambios"
        git push
